name: CloneTest_zissekiti

on: 
 workflow_dispatch:
     inputs:  
      apllicationname:
       required: true
       type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
    
     - name: Preparing Repositories
       uses: actions/checkout@v2
       with:
        repository: "yaraiOrg03/test2"
     - name: test   
       run: cd ${{github.workspace}};ls
      
     - name: Setup MSBuild.exe
       uses: microsoft/setup-msbuild@v1

      # nuget のセットアップをする
     - name: Setup NuGet
       uses: NuGet/setup-nuget@v1

      # solution ファイルの状態を復元する
      # 例えば、nuget で参照しているファイルを取得するなど
     - name: Restore the application
      # run: msbuild /t:Restore /p:Configuration=Release
       run: nuget restore hotel_groupB.sln

      # Build 実行
     - name: Build the application
       run: msbuild /p:Configuration=Release
      
    # - name: Setup .NET
     #  uses: warrenbuckley/setup-MSBuild@v1
      # with:
       # dotnet-version: 4.7.2
     #- name: Restore dependencies
      # run: dotnet restore
     #- name: Build
     #  run: dotnet build --no-restore
     - name: test   
       run: cd ${{github.workspace}};ls
   
     - name: Install AzureSignTool
       run: dotnet tool install --global AzureSignTool
     - name: Sign package
       run:
              AzureSignTool sign -kvt "${{secrets.AzureKeyVaultTenantId}}" -kvu "${{ secrets.AzureKeyVaultUrl }}" -kvi "${{ secrets.AzureKeyVaultClientId }}" -kvs "${{ secrets.AzureKeyVaultClientSecret }}" -kvc ${{ secrets.AzureKeyVaultName }} -tr http://timestamp.digicert.com -v "${{github.workspace}}/hotel_groupB/bin/Debug/${{github.event.inputs.apllicationname}}"
     
     - name: Archive production artifacts
       uses: actions/upload-artifact@v2
       with:
          name: 39
          path: "${{github.workspace}}/hotel_groupB/bin/Debug/${{github.event.inputs.apllicationname}}"
